version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: 'zookeeper'
    ports:
      - "2181:2181"
    networks:
      - local-network
  kafka:
    image: wurstmeister/kafka
    container_name: 'kafka'
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - local-network
  message_generator:
    build: .
    container_name: 'message_generator'
    depends_on:
      - kafka
    networks:
      - local-network
    environment:
      KAFKA_BROKER: "kafka"
      KAFKA_BROKER_PORT: 9092
      KAFKA_TARGET_TOPIC: "test-message-generator"
      MESSAGE_SEND_INTERVAL: 5
      LOG_LEVEL: "INFO"
      LOG_FORMAT: "%(asctime)-15s %(message)s"
      LOG_FILE_PATH: "/var/log/test_message_generator.log"
networks:
  local-network:
    driver: "bridge"
