version: '3.7'
services:
  test-zookeeper:
    image: wurstmeister/zookeeper
    container_name: 'zookeeper'
    ports:
      - '2181:2181'
    networks:
      - 'test-network'
  test-kafka:
    image: wurstmeister/kafka
    container_name: 'test-kafka'
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 'test-kafka'
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - 'test-network'
  message_generator:
    build: .
    container_name: 'message_generator'
    depends_on:
      - 'test-kafka'
    networks:
      - 'test-network'
    environment:
      KAFKA_BROKER_HOST: "test-kafka"
      KAFKA_BROKER_PORT: 9092
      KAFKA_TARGET_TOPIC: "test-message-generator"
      MESSAGE_SEND_INTERVAL: 5
      LOG_LEVEL: "INFO"
      LOG_FORMAT: "%(asctime)-15s %(message)s"
      LOG_FILE_PATH: "/var/log/test_message_generator.log"
    entrypoint: 'python3 message_generator/__main__.py'
    restart: always
  test-reciever:
    build: .
    container_name: 'test-receiver'
    depends_on:
      - 'test-kafka'
    networks:
      - 'test-network'
    environment:
      KAFKA_BROKER_HOST: 'test-kafka'
      KAFKA_BROKER_PORT: 9092
      KAFKA_TARGET_TOPIC: 'test-message-generator'
      MESSAGE_SEND_INTERVAL: 5
      LOG_LEVEL: 'INFO'
      LOG_FORMAT: '%(asctime)-15s %(message)s'
      LOG_FILE_PATH: '/var/log/test_message_generator.log'
    entrypoint: 'python3 message_generator/test_receiver.py'
    restart: always
networks:
  test-network:
    driver: 'bridge'
